# =======================================================
# Standard-Definition für den "Minuto-Gutschein"
# =======================================================

# Metadaten zur eindeutigen Identifikation des Standards.
[metadata]
name = "Minuto-Gutschein"             # Offizieller Name des Standards.
uuid = "MINUTO-V1-XXXX-YYYY"           # Eindeutige ID des Standards.
abbreviation = "Minuto"                # Gängige Abkürzung.

# ---

# Template-Werte, die bei der Erstellung in einen neuen Gutschein kopiert werden.
# Aufgeteilt in feste (nicht überschreibbare) und Standardwerte (überschreibbar).

[template.fixed]
# Die Beschreibung kann den Platzhalter {{amount}} enthalten, der zur Laufzeit ersetzt wird.
description = "Ein Gutschein für Waren oder Dienstleistungen im Wert von {{amount}} Minuten qualitativer Leistung."
footnote = "Gutschein-Nutzung nur für Mitspieler/innen."
primary_redemption_type = "goods_or_services"
is_divisible = true
round_up_validity_to = "P1Y" # Gültigkeit auf Jahresende aufrunden.

# Vorgaben für den Nennwert.
[template.fixed.nominal_value]
unit = "Minuto" # Die Einheit ist durch den Standard fest vorgegeben.

# Vorgaben für die Besicherung. Beim Minuto sind diese leer.
[template.fixed.collateral]
type = ""             #
description = ""      #
redeem_condition = "" #

# Vorgaben für die Bürgen.
[template.fixed.guarantor_info]
needed_count = 2 #
description = "Ein männlicher und ein weiblicher Bürge sind erforderlich." #

[template.default]
default_validity_duration = "P5Y" # Standard-Gültigkeit von 5 Jahren.

# Validierungsregeln, die zur Überprüfung eines Gutscheins verwendet, aber nicht kopiert werden.
[validation]
issuance_minimum_validity_duration = "P3Y" # Mindestgültigkeit bei Ausgabe: 3 Jahre.
amount_decimal_places = 0 # Minuten sind nicht teilbar.
allowed_transaction_types = ["init", "split", "redeem"]
required_voucher_fields = [
  "voucher_id",
  "creation_date",
  "creator.signature",
  "guarantor_signatures", # Bürgen-Signaturen sind für einen Minuto zwingend erforderlich.
]

# Spezifische Regeln für die Bürgen-Validierung.
[validation.guarantor_rules]
gender_specific = true      # Die Geschlechter der Bürgen werden geprüft.
genders_needed = ["1", "2"] # Ein männlicher (1) und ein weiblicher (2) Bürge sind nötig.
