# =================================================================================
# Vorlage für Gutschein-Standard-Definitionen (standard_template.toml)
# =================================================================================
#
# Diese Datei dient als umfassende Dokumentation und Kopiervorlage zur Erstellung
# neuer, signierter Gutschein-Standards. Sie erklärt alle verfügbaren Felder.
#
# Ein Standard ist in vier Hauptblöcke unterteilt:
# 1. [metadata]:    Beschreibt den Standard selbst.
# 2. [template]:    Definiert Werte, die als Vorlage für neue Gutscheine dienen.
# 3. [validation]:  Legt Regeln fest, anhand derer Gutscheine validiert werden.
# 4. [signature]:   Enthält die kryptographische Signatur des Herausgebers.
#

# =================================================================================
# Block 1: Metadaten
# =================================================================================
#
# Enthält allgemeine, identifizierende Informationen über den Standard.
#
[metadata]
# (String) Der offizielle, menschenlesbare Name des Standards.
name = "Name des Standards (z.B. Regional-Taler)"

# (String) Eine global eindeutige ID für diesen Standard.
# Es wird empfohlen, hier eine Version und ein Datum zu verwenden.
uuid = "STANDARD-NAME-V1-YYYY-MM"

# (String) Eine gängige Abkürzung für die Nennwert-Einheit des Gutscheins.
abbreviation = "RT"

# (String, NEU) Der Name des offiziellen Herausgebers des Standards.
issuer_name = "Name des Herausgebers (z.B. Community Council)"

# (String, Optional, NEU) Eine URL zur Homepage des Standards oder der Community.
homepage_url = "https://example.com/standard-info"

# (String, Optional, NEU) Eine URL zur technischen Dokumentation des Standards.
documentation_url = "https://example.com/standard-docs"

# (Array von Strings, Optional, NEU) Suchbegriffe zur Kategorisierung.
keywords = ["keyword1", "keyword2", "community-currency"]


# =================================================================================
# Block 2: Template (Vorlage)
# =================================================================================
#
# Definiert Werte, die bei der Erstellung eines neuen Gutscheins als Vorlage dienen.
#
[template.fixed]
# (Array von Tabellen, NEU) Eine menschenlesbare, mehrsprachige Beschreibung.
# Jede Tabelle muss einen `lang`-Code (ISO 639-1) und den `text` enthalten.
# Der Platzhalter {{amount}} wird bei der Erstellung automatisch ersetzt.
# Englisch ("en") sollte als internationaler Fallback immer vorhanden sein.
[[template.fixed.description]]
lang = "de"
text = "Gutschein für Waren oder Dienstleistungen im Wert von {{amount}} Einheiten."

[[template.fixed.description]]
lang = "en"
text = "A voucher for goods or services worth {{amount}} units."

# (String, Optional) Ein kurzer Fußnotentext, der auf dem Gutschein angezeigt wird.
footnote = "Optionaler Fußnotentext."

# (String) Definiert den primären Zweck, für den der Gutschein eingelöst werden kann.
primary_redemption_type = "goods_or_services"

# (Boolean) Gibt an, ob die Nennwerte von Gutscheinen dieses Standards addierbar sind ("summable").
#
# true:  Werte sind wie Währung und repräsentieren eine Menge einer einheitlichen
#        Einheit (z.B. "Minuten", "Unzen"). Sie können sinnvoll addiert
#        werden (10 Unzen + 20 Unzen = 30 Unzen).
#
# false: Werte sind wie einzigartige Tickets und repräsentieren einen
#        spezifischen, nicht austauschbaren Anspruch (z.B. "1 Haarschnitt",
#        "1 Konzertkarte für Platz A1"). Das Addieren der Werte ergibt keinen Sinn.
is_summable = true

# (Boolean) Gibt an, ob der Gutschein teilbar ist.
is_divisible = true

# (String, Optional) Regel zur Aufrundung des Gültigkeitsdatums ("P1D", "P1M", "P1Y").
round_up_validity_to = "P1M"

[template.fixed.nominal_value]
# (String) Die Einheit des Nennwerts, die für diesen Standard zwingend ist.
unit = "Regional-Taler"

[template.fixed.collateral]
# (String) Die Art der Besicherung.
type = "Keine"
# (String) Eine allgemeine Beschreibung der Besicherung.
description = "Dieser Gutschein ist durch das Vertrauen der Gemeinschaft besichert."
# (String) Die Bedingungen, unter denen die Besicherung eingefordert werden kann.
redeem_condition = "Nicht zutreffend."

[template.fixed.guarantor_info]
# (Integer) Die Anzahl der benötigten Bürgen für diesen Gutschein.
needed_count = 2
# (String) Eine menschenlesbare Beschreibung der Bürgenanforderungen.
description = "Zwei Bürgen aus der Community sind erforderlich."

# ---

[template.default]
# (String, Optional) Die Standard-Gültigkeitsdauer im ISO 8601-Format.
default_validity_duration = "P5Y"


# =================================================================================
# Block 3: Validierungsregeln
# =================================================================================
#
# Legt die Regeln fest, nach denen ein Gutschein dieses Standards validiert wird.
# Die gesamte `[validation]`-Sektion ist optional. Wenn sie fehlt, werden keine
# dieser spezifischen Prüfungen durchgeführt.
#
[validation]
#
# # -- Sektion für quantitative Regeln --
# [validation.counts]
# # Legt die minimale und maximale Anzahl für bestimmte Elemente fest.
# guarantor_signatures = { min = 1, max = 3 }
# additional_signatures = { min = 0, max = 5 }
# transactions = { min = 1, max = 100 } # z.B. um die Dateigröße zu begrenzen
#
# # -- Sektion für Signatur-Anforderungen --
# # Definiert spezifische, erforderliche Signaturen von bestimmten Parteien.
# [[validation.required_signatures]]
# # Eine menschenlesbare Beschreibung der Rolle des Unterzeichners.
# role_description = "Signatur der ausgebenden Institution"
# # Eine Liste von `did:key`-IDs, die zur Unterzeichnung berechtigt sind.
# allowed_signer_ids = ["did:key:z...", "did:key:z..."]
# # Optional: Die Signatur muss exakt diesen `description`-Text enthalten.
# required_signature_description = "Offizielle Freigabe"
# # Wenn `true`, muss eine passende Signatur zwingend vorhanden sein.
# is_mandatory = true
#
# # -- Sektion für Inhalts-Regeln --
# [validation.content_rules]
#   # Definiert Felder, die einen exakten, festen Wert haben müssen.
#   [validation.content_rules.fixed_fields]
#   # Der Key ist ein JSON-Pfad. Der Wert muss ein gültiger JSON-Wert sein.
#   "nominal_value.unit" = "Euro"
#   "divisible" = false
#
#   # Definiert Felder, deren Wert aus einer vorgegebenen Liste stammen muss.
#   [validation.content_rules.allowed_values]
#   "nominal_value.amount" = ["25", "50", "100"]
#
#   # Definiert Felder, deren Wert einem bestimmten Regex-Muster entsprechen muss.
#   [validation.content_rules.regex_patterns]
#   # Beispiel: Rechnungsnummer im Format RE-YYYY-NNNNNN
#   description = '^RE-202[5-9]-[0-9]{6}$'
#
# # -- Sektion für Verhaltens-Regeln --
# [validation.behavior_rules]
# # Legt fest, welche Transaktionstypen (`t_type`) erlaubt sind.
# allowed_t_types = ["transfer", "split", "redeem"]
#
# # Legt die maximal erlaubte Gültigkeitsdauer ab Erstellung fest (ISO 8601 Duration).
# # Verhindert, dass Gutscheine mit unrealistisch langer Lebensdauer erstellt werden.
# max_creation_validity_duration = "P10Y" # z.B. maximal 10 Jahre

# =================================================================================
# Block 4: Kryptographische Signatur (NEU & ZWINGEND ERFORDERLICH)
# =================================================================================
#
# Dieser Block enthält die digitale Signatur des Herausgebers, die die
# Authentizität und Integrität dieser gesamten Standard-Datei beweist.
#
[signature]
# (String) Die `did:key` des Herausgebers. Sie enthält den öffentlichen
# Schlüssel, der zur Verifizierung der Signatur verwendet wird.
# Format: "did:key:z..."
issuer_id = "did:key:z...PublicKeyDesHerausgebers..."

# (String) Die finale Base58-kodierte Ed25519-Signatur.
# Sie signiert den SHA3-256 Hash des kanonisierten Inhalts dieser Datei
# (ohne den [signature]-Block selbst).
signature = "Base58EncodedSignature..."