[metadata]
abbreviation = "Minuto"
documentation_url = "https://github.com/minuto/standards/tree/main/minuto_v1"
homepage_url = "https://minuto.org/standard-info"
issuer_name = "Minuto Community Council"
keywords = [
    "community-currency",
    "time-based",
    "mutual-credit",
    "b2b",
]
name = "Minuto-Gutschein"
uuid = "MINUTO-V1-2025-09"

[template.default]
default_validity_duration = "P5Y"

[template.fixed]
footnote = "Gutschein-Nutzung nur für Mitspieler/innen."
is_divisible = true
is_summable = true
primary_redemption_type = "goods_or_services"
round_up_validity_to = "P1Y"

[template.fixed.collateral]
description = ""
redeem_condition = ""
type = ""

[[template.fixed.description]]
lang = "de"
text = "Ein Gutschein für Waren oder Dienstleistungen im Wert von {{amount}} Minuten qualitativer Leistung."

[[template.fixed.description]]
lang = "en"
text = "A voucher for goods or services worth {{amount}} minutes of quality performance."

[template.fixed.guarantor_info]
description = "Ein männlicher und ein weiblicher Bürge sind erforderlich."
needed_count = 2

[template.fixed.nominal_value]
unit = "Minuto"

[validation]
[validation.counts]
# Erzwingt exakt zwei Bürgen-Signaturen, wie in `needed_count` beschrieben.
guarantor_signatures = { min = 2, max = 2 }

[validation.behavior_rules]
allowed_t_types = [
    "init",
    "split",
    "transfer",
    "redeem",
]
amount_decimal_places = 0
issuance_minimum_validity_duration = "P3Y"

# NEU: Erzwingt, dass von den zwei Bürgen exakt einer männlich ('1')
# und einer weiblich ('2') sein muss, gemäß ISO 5218.
[validation.field_group_rules]
[validation.field_group_rules.guarantor_signatures]
field = "gender"
value_counts = [
    { value = "1", min = 1, max = 1 },
    { value = "2", min = 1, max = 1 },
]

[signature]
# Die `did:key` des Herausgebers, die seinen öffentlichen Schlüssel enthält.
issuer_id = "1oB@did:key:z6Mkoim7ZGcaKdoeD41USV5gmxfiVXXiPDeYt4T9rnEB5zfM"

# Die finale Base58-kodierte Ed25519-Signatur des kanonisierten Inhalts (ohne diesen Block).
signature = "2pMQNQMj3q5Eqsv6nsLwc7kFNhSb17LCLxQG1v3bWWaaFEKkE8RGWf1SVa3CSRfJJrZShkX5nEui57iXGhZzQEVv"
